import { ProjectState, CustomPostType, Taxonomy, MetaField, FieldType, CustomEndpoint } from '../types';
import { generateSeederBody } from './dataGenerator';

export const generatePackageJSON = (project: ProjectState): string => {
  const pkg = {
    "name": project.name.toLowerCase().replace(/\s+/g, '-'),
    "version": "1.0.0",
    "description": "WordPress Plugin generated by WP API Architect",
    "scripts": {
      "build": "wp-scripts build",
      "format": "wp-scripts format",
      "lint:css": "wp-scripts lint-style",
      "lint:js": "wp-scripts lint-js",
      "packages-update": "wp-scripts packages-update",
      "plugin-zip": "wp-scripts plugin-zip",
      "start": "wp-scripts start"
    },
    "devDependencies": {
      "@wordpress/scripts": "^26.0.0"
    }
  };
  return JSON.stringify(pkg, null, 2);
};

export const generateComposerJSON = (project: ProjectState): string => {
  const composer = {
    "name": `wp-architect/${project.name.toLowerCase().replace(/\s+/g, '-')}`,
    "description": "WordPress Plugin generated by WP API Architect",
    "type": "wordpress-plugin",
    "license": "GPL-2.0-or-later",
    "authors": [
      {
        "name": "WP API Architect",
        "email": "architect@example.com"
      }
    ],
    "require": {
      "php": ">=7.4"
    }
  };
  return JSON.stringify(composer, null, 2);
};

// Helper to generate schema for nested fields
const generateFieldSchema = (field: MetaField): string => {
  if (field.type === FieldType.REPEATER) {
    let schema = `array(\n`;
    schema += `\t\t\t\t\t'type' => 'array',\n`;
    schema += `\t\t\t\t\t'items' => array(\n`;
    schema += `\t\t\t\t\t\t'type' => 'object',\n`;
    schema += `\t\t\t\t\t\t'properties' => array(\n`;
    
    field.subFields?.forEach(sub => {
       // Recurse or simple type
       const subType = sub.type === FieldType.INTEGER ? 'integer' : sub.type === FieldType.NUMBER ? 'number' : sub.type === FieldType.BOOLEAN ? 'boolean' : 'string';
       schema += `\t\t\t\t\t\t\t'${sub.key}' => array( 'type' => '${subType}' ),\n`;
    });

    schema += `\t\t\t\t\t\t),\n`;
    schema += `\t\t\t\t\t),\n`;
    schema += `\t\t\t\t)`;
    return schema;
  }
  
  // Standard types
  const schemaType = field.type === FieldType.INTEGER || field.type === FieldType.RELATIONSHIP ? 'integer' : field.type === FieldType.NUMBER ? 'number' : field.type === FieldType.BOOLEAN ? 'boolean' : 'string';
  return `array( 'type' => '${schemaType}', 'description' => '${field.description.replace(/'/g, "\\'")}' )`;
};

export const generatePHP = (project: ProjectState): string => {
  const { postTypes, taxonomies, customEndpoints, namespace, globalHelpers } = project;
  const projectSlug = project.name.toLowerCase().replace(/\s+/g, '_');
  const timestamp = new Date().toISOString();

  let php = `<?php
/**
 * Plugin Name: ${project.name}
 * Description: Auto-generated by WP API Architect. Includes Custom Post Types, REST Endpoints, and Logic.
 * Version: 1.0.0
 * Author: WP API Architect
 * Generated: ${timestamp}
 */

if ( ! defined( 'ABSPATH' ) ) {
\texit; // Exit if accessed directly.
}

// =========================================================================
// 1. GLOBAL LOGIC, HOOKS & HELPER MODULES
// =========================================================================
`;

  if (globalHelpers && globalHelpers.length > 0) {
    globalHelpers.forEach(helper => {
       const type = helper.type || 'function';
       const priority = helper.priority ?? 10;
       const acceptedArgs = helper.acceptedArgs ?? 1;
       const hookName = helper.hookName || 'init';
       const paramList = helper.parameters || '';

       if (type === 'action') {
         php += `/**\n * [Action Hook] ${hookName} -> ${helper.name}\n * ${helper.description || 'Custom Action Hook'}\n */\n`;
         php += `add_action( '${hookName}', '${helper.name}', ${priority}, ${acceptedArgs} );\n`;
         php += `if ( ! function_exists( '${helper.name}' ) ) {\n`;
         php += `\tfunction ${helper.name}( ${paramList} ) {\n`;
         php += helper.phpCode.split('\n').map(line => `\t\t${line.trimStart()}`).join('\n') + '\n';
         php += `\t}\n}\n\n`;
       } else if (type === 'filter') {
         php += `/**\n * [Filter Hook] ${hookName} -> ${helper.name}\n * ${helper.description || 'Custom Filter Hook'}\n */\n`;
         php += `add_filter( '${hookName}', '${helper.name}', ${priority}, ${acceptedArgs} );\n`;
         php += `if ( ! function_exists( '${helper.name}' ) ) {\n`;
         php += `\tfunction ${helper.name}( ${paramList} ) {\n`;
         php += helper.phpCode.split('\n').map(line => `\t\t${line.trimStart()}`).join('\n') + '\n';
         php += `\t}\n}\n\n`;
       } else if (type === 'middleware') {
         php += `/**\n * [REST API Pre-Dispatch Middleware] ${helper.name}\n * ${helper.description || 'Global REST Middleware'}\n */\n`;
         php += `add_filter( 'rest_pre_dispatch', '${helper.name}', ${priority}, 3 );\n`;
         php += `if ( ! function_exists( '${helper.name}' ) ) {\n`;
         php += `\tfunction ${helper.name}( $result, $server, $request ) {\n`;
         php += helper.phpCode.split('\n').map(line => `\t\t${line.trimStart()}`).join('\n') + '\n';
         php += `\t}\n}\n\n`;
       } else if (type === 'class') {
         php += `/**\n * [OOP Module Class] ${helper.name}\n * ${helper.description || 'Modern OOP Module'}\n */\n`;
         php += `if ( ! class_exists( '${helper.name}' ) ) {\n`;
         php += `\tclass ${helper.name} {\n`;
         php += helper.phpCode.split('\n').map(line => `\t\t${line.trimStart()}`).join('\n') + '\n';
         php += `\t}\n`;
         php += `\tif ( method_exists( '${helper.name}', 'init' ) ) {\n`;
         php += `\t\t${helper.name}::init();\n`;
         php += `\t}\n`;
         php += `}\n\n`;
       } else {
         // Standard helper function
         php += `/**\n * [Helper Function] ${helper.name}\n * ${helper.description || helper.name}\n */\n`;
         php += `if ( ! function_exists( '${helper.name}' ) ) {\n`;
         php += `\tfunction ${helper.name}( ${paramList} ) {\n`;
         php += helper.phpCode.split('\n').map(line => `\t\t${line.trimStart()}`).join('\n') + '\n';
         php += `\t}\n}\n\n`;
       }
    });
  }

  php += `
// =========================================================================
// 2. CONTENT DEFINITIONS (CPT & TAXONOMIES)
// =========================================================================

add_action( 'init', '${projectSlug}_register_content' );

function ${projectSlug}_register_content() {
`;

  // Register Taxonomies
  taxonomies.forEach((tax) => {
    php += `
\t// Taxonomy: ${tax.pluralName}
\tregister_taxonomy( '${tax.slug}', ${JSON.stringify(tax.connectedPostTypes)}, array(
\t\t'labels' => array(
\t\t\t'name' => '${tax.pluralName}',
\t\t\t'singular_name' => '${tax.singularName}',
\t\t),
\t\t'hierarchical' => ${tax.hierarchical ? 'true' : 'false'},
\t\t'show_in_rest' => ${tax.showInRest ? 'true' : 'false'},
\t) );
`;
  });

  // Register Post Types
  postTypes.forEach((cpt) => {
    php += `
\t// Post Type: ${cpt.pluralName}
\tregister_post_type( '${cpt.slug}', array(
\t\t'labels' => array(
\t\t\t'name' => '${cpt.pluralName}',
\t\t\t'singular_name' => '${cpt.singularName}',
\t\t),
\t\t'public' => true,
\t\t'has_archive' => true,
\t\t'menu_icon' => 'dashicons-${cpt.icon}',
\t\t'supports' => array( ${cpt.supports.map((s) => `'${s}'`).join(', ')} ),
\t\t'show_in_rest' => ${cpt.showInRest ? 'true' : 'false'},
\t\t'rest_base' => '${cpt.restBase}',
\t) );
`;
  });

  php += `}\n\n`;

  // Register Meta Fields
  if (postTypes.some(pt => pt.metaFields.length > 0)) {
    php += `add_action( 'init', '${projectSlug}_register_meta' );\n`;
    php += `function ${projectSlug}_register_meta() {\n`;

    postTypes.forEach((cpt) => {
      cpt.metaFields.forEach((field) => {
        if (field.showInRest) {
          const type = field.type === FieldType.REPEATER ? 'array' : field.type === FieldType.INTEGER || field.type === FieldType.RELATIONSHIP ? 'integer' : field.type === FieldType.NUMBER ? 'number' : field.type === FieldType.BOOLEAN ? 'boolean' : 'string';
          
          php += `
\tregister_post_meta( '${cpt.slug}', '${field.key}', array(
\t\t'show_in_rest' => array(
\t\t\t'schema' => ${generateFieldSchema(field)}
\t\t),
\t\t'single' => true,
\t\t'type' => '${type}',
\t) );
`;
        }
      });
    });

    php += `}\n\n`;
  }

  // =========================================================================
  // 3. REST API ENDPOINTS
  // =========================================================================

  if (customEndpoints.length > 0) {
    const apiVer = project.apiVersion || 'v1';
    const fullNamespace = `${namespace}/${apiVer}`;

    php += `add_action( 'rest_api_init', '${projectSlug}_register_routes' );\n\n`;
    php += `function ${projectSlug}_register_routes() {\n`;
    
    customEndpoints.forEach(endpoint => {
      const cleanRoute = endpoint.route.startsWith('/') ? endpoint.route : '/' + endpoint.route;

      php += `
\tregister_rest_route( '${fullNamespace}', '${cleanRoute}', array(
\t\t'methods' => '${endpoint.method}',
\t\t'callback' => '${endpoint.callbackFunction}',
\t\t'permission_callback' => '__return_true', 
\t\t'args' => array(
${endpoint.parameters.map(param => `\t\t\t'${param.key}' => array(
\t\t\t\t'required' => ${param.required ? 'true' : 'false'},
\t\t\t\t'type' => '${param.type}',
\t\t\t\t'description' => '${param.description.replace(/'/g, "\\'")}',
\t\t\t),`).join('\n')}
\t\t),
\t) );
`;
    });

    php += `}\n\n`;

    // Generate Callback Implementation
    customEndpoints.forEach(endpoint => {
      php += `/**\n * Handler for ${endpoint.method} ${endpoint.route}\n */\n`;
      php += `function ${endpoint.callbackFunction}( $request ) {\n`;

      // 0. Middleware Routines
      if (endpoint.middlewares && endpoint.middlewares.length > 0) {
        const activeMws = endpoint.middlewares.filter(m => m.enabled);
        if (activeMws.length > 0) {
          php += `\t// 0. Middleware Pre-Callback Checks\n`;
          activeMws.forEach(mw => {
            php += `\t// Middleware: ${mw.name}\n`;
            php += mw.callbackSnippet.split('\n').map(line => `\t${line}`).join('\n') + '\n\n';
          });
        }
      }

      php += `\t// 1. Parse Parameters\n`;
      endpoint.parameters.forEach(param => {
        php += `\t$${param.key} = $request->get_param( '${param.key}' );\n`;
      });

      // Storage Logic Generation
      if (endpoint.storage?.enabled && endpoint.method !== 'GET') {
        php += `\n\t// 2. Storage Automator (${endpoint.storage.targetCptSlug})\n`;
        php += `\t$post_data = array(\n`;
        php += `\t\t'post_type'   => '${endpoint.storage.targetCptSlug}',\n`;
        php += `\t\t'post_status' => 'publish',\n`;
        
        Object.entries(endpoint.storage.fieldMapping).forEach(([paramKey, metaKey]) => {
           if (metaKey === 'post_title') {
             php += `\t\t'post_title'  => $${paramKey},\n`;
           }
           if (metaKey === 'post_content') {
             php += `\t\t'post_content'  => $${paramKey},\n`;
           }
        });
        php += `\t);\n\n`;
        php += `\t$post_id = wp_insert_post( $post_data );\n\n`;
        
        php += `\tif ( ! is_wp_error( $post_id ) ) {\n`;
        Object.entries(endpoint.storage.fieldMapping).forEach(([paramKey, metaKey]) => {
           if (metaKey !== 'post_title' && metaKey !== 'post_content') {
             php += `\t\tupdate_post_meta( $post_id, '${metaKey}', $${paramKey} );\n`;
           }
        });
        php += `\t}\n`;
      } else {
        // Fallback for when storage is not enabled but we need a 'post_id' placeholder for consistency if hooks use it?
        // No, keep it clean.
      }

      // Custom PHP Execution
      if (endpoint.customPhp) {
        php += `\n\t// 3. Custom Logic\n`;
        php += `\t${endpoint.customPhp.split('\n').join('\n\t')}\n`;
      }

      // Actions
      if (endpoint.hookName) {
        const actionArgs = endpoint.storage?.enabled ? `array( 'request' => $request, 'post_id' => $post_id )` : `$request`;
        php += `\n\t// 4. Hook Fire\n`;
        php += `\tdo_action( '${endpoint.hookName}', ${actionArgs} );\n`;
      }
      
      php += `\n\treturn new WP_REST_Response( array(\n\t\t'success' => true,\n\t\t'message' => 'Processed ${endpoint.route}',\n`;
      if (endpoint.storage?.enabled) {
         php += `\t\t'resource_id' => $post_id\n`;
      }
      php += `\t), 200 );\n`;
      php += `}\n\n`;
    });
  }

  return php;
};

export const generatePlaygroundBlueprint = (project: ProjectState): string => {
  const phpCode = generatePHP(project);
  const projectSlug = project.name.toLowerCase().replace(/\s+/g, '-');
  const seederCode = generateSeederBody(project);
  
  const blueprint = {
    "landingPage": "/wp-admin/edit.php?post_type=" + (project.postTypes[0]?.slug || 'post'),
    "preferredVersions": {
      "php": "8.0",
      "wp": "latest"
    },
    "steps": [
      {
        "step": "login",
        "username": "admin",
        "password": "password"
      },
      {
        "step": "runPHP",
        "code": "if (!is_dir('/wordpress/wp-content/plugins/${projectSlug}')) { mkdir('/wordpress/wp-content/plugins/${projectSlug}', 0755, true); }"
      },
      {
        "step": "writeFile",
        "path": `/wordpress/wp-content/plugins/${projectSlug}/index.php`,
        "data": phpCode
      },
      {
        "step": "activatePlugin",
        "pluginName": projectSlug,
        "pluginPath": `${projectSlug}/index.php`
      },
      {
        "step": "runPHP",
        "code": `
          // Seed Data
          ${seederCode}
          
          // Final check
          $types = get_post_types(['_builtin' => false]);
          echo "Setup Complete. Active CPTs: " . implode(', ', $types);
        `
      }
    ]
  };

  return JSON.stringify(blueprint, null, 2);
};

export const generateOpenAPI = (project: ProjectState): string => {
  const paths: any = {};
  const schemas: any = {};

  // 1. CPT Paths
  project.postTypes.forEach((cpt) => {
    if (!cpt.showInRest) return;

    // Define Schema
    const properties: any = {
      id: { type: 'integer', readOnly: true },
      date: { type: 'string', format: 'date-time' },
      status: { type: 'string' },
      type: { type: 'string' },
      link: { type: 'string', format: 'uri', readOnly: true },
      title: { 
        type: 'object', 
        properties: { rendered: { type: 'string' } } 
      },
    };

    if (cpt.supports.includes('editor')) {
      properties.content = { 
        type: 'object', 
        properties: { rendered: { type: 'string' }, protected: { type: 'boolean' } } 
      };
    }

    if (cpt.supports.includes('excerpt')) {
      properties.excerpt = { 
        type: 'object', 
        properties: { rendered: { type: 'string' }, protected: { type: 'boolean' } } 
      };
    }

    // Custom Fields
    cpt.metaFields.forEach(field => {
      if (field.showInRest) {
        properties[field.key] = {
          type: field.type === FieldType.RELATIONSHIP ? 'integer' : field.type,
          description: field.description
        };
      }
    });

    // Associated Taxonomies
    cpt.taxonomies.forEach(taxSlug => {
       properties[taxSlug] = {
         type: 'array',
         items: { type: 'integer' },
         description: `IDs of ${taxSlug} terms assigned to the post.`
       };
    });

    schemas[cpt.singularName] = {
      type: 'object',
      properties: properties
    };

    // Define Paths
    const pathBase = `/wp/v2/${cpt.restBase}`;
    
    // Collection Endpoint
    paths[pathBase] = {
      get: {
        summary: `Retrieve a list of ${cpt.pluralName}`,
        tags: [cpt.pluralName],
        responses: {
          '200': {
            description: `List of ${cpt.pluralName}`,
            content: {
              'application/json': {
                schema: {
                  type: 'array',
                  items: { $ref: `#/components/schemas/${cpt.singularName}` }
                }
              }
            }
          }
        }
      },
      post: {
        summary: `Create a new ${cpt.singularName}`,
        tags: [cpt.pluralName],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { $ref: `#/components/schemas/${cpt.singularName}` }
            }
          }
        },
        responses: {
          '201': {
            description: `${cpt.singularName} created`,
            content: {
              'application/json': {
                schema: { $ref: `#/components/schemas/${cpt.singularName}` }
              }
            }
          }
        }
      }
    };

    // Single Endpoint
    paths[`${pathBase}/{id}`] = {
      get: {
        summary: `Retrieve a single ${cpt.singularName}`,
        tags: [cpt.pluralName],
        parameters: [{
          name: 'id',
          in: 'path',
          required: true,
          schema: { type: 'integer' }
        }],
        responses: {
          '200': {
            description: `A single ${cpt.singularName}`,
            content: {
              'application/json': {
                schema: { $ref: `#/components/schemas/${cpt.singularName}` }
              }
            }
          }
        }
      },
      post: {
        summary: `Update a ${cpt.singularName}`,
        tags: [cpt.pluralName],
        parameters: [{
          name: 'id',
          in: 'path',
          required: true,
          schema: { type: 'integer' }
        }],
        requestBody: {
           content: {
             'application/json': {
               schema: { $ref: `#/components/schemas/${cpt.singularName}` }
             }
           }
        },
        responses: {
          '200': {
            description: `${cpt.singularName} updated`,
             content: {
              'application/json': {
                schema: { $ref: `#/components/schemas/${cpt.singularName}` }
              }
            }
          }
        }
      },
       delete: {
        summary: `Delete a ${cpt.singularName}`,
        tags: [cpt.pluralName],
        parameters: [{
          name: 'id',
          in: 'path',
          required: true,
          schema: { type: 'integer' }
        }],
        responses: {
          '200': {
             description: `${cpt.singularName} deleted`,
          }
        }
      }
    };
  });

  // 2. Custom Endpoint Paths
  const apiVer = project.apiVersion || 'v1';
  project.customEndpoints.forEach(endpoint => {
    const route = `/${project.namespace}/${apiVer}${endpoint.route.startsWith('/') ? endpoint.route : '/' + endpoint.route}`;
    
    // Initialize path if not exists
    if (!paths[route]) {
      paths[route] = {};
    }

    const parameters = endpoint.parameters.map(p => ({
      name: p.key,
      in: endpoint.method === 'GET' ? 'query' : 'body', // Simplified
      required: p.required,
      description: p.description,
      schema: { type: p.type }
    }));

    paths[route][endpoint.method.toLowerCase()] = {
      summary: endpoint.description || `Custom endpoint for ${endpoint.route}`,
      tags: ['Custom Endpoints'],
      parameters: endpoint.method === 'GET' ? parameters : [],
      requestBody: endpoint.method !== 'GET' && parameters.length > 0 ? {
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: endpoint.parameters.reduce((acc: any, p) => {
                acc[p.key] = { type: p.type, description: p.description };
                return acc;
              }, {})
            }
          }
        }
      } : undefined,
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: { type: 'object' }
            }
          }
        }
      }
    };
  });

  const spec = {
    openapi: '3.0.0',
    info: {
      title: project.name,
      version: '1.0.0',
      description: `Generated REST API for ${project.name}`
    },
    paths: paths,
    components: {
      schemas: schemas
    }
  };

  return JSON.stringify(spec, null, 2);
};
